import React, { useState, useEffect, useRef } from "react";
import { useRouter } from "next/dist/client/router";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";

export interface ProjectProps {}

export default function ProjectPage(props: ProjectProps) {
  const router = useRouter()
  return (
    <div>
      <Head>
        <title>ProjectPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      ProjectPage
    </div>
  );
}
