import type { NextPage } from 'next';
import React, { useState, useEffect, useRef } from "react";
import Head from 'next/head';
import Banner from "components/custom/Banner";
import AuthenticationSection from 'components/custom/AuthSection';
import ListProjectSection from 'components/custom/ListProjectSection';
import ProcessNFTSection from 'components/custom/ProcessNFTSection';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>D App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner />
        <AuthenticationSection />
        <ListProjectSection />
        <ProcessNFTSection />
      </main>
    </div>
  )
}

export default Home
