import Head from 'next/head';
import Footer from "components/display/Footer";
import Header from 'components/display/Header';
import BoxProjectDetail from 'components/custom/ProjectDetail';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export default function ProjectDetail() {
  return (
    <div>
      <Head>
        <title>Project Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header theme={'black'}/>
        <BoxProjectDetail project={project_detail}/>
      </main>

      <Footer />

    </div>
  )
}

const project_detail = {
  id: 1,
  img_logo_path: 'logo-img-project-detail.png',
  name: 'Jadelabs',
  name_company: 'Jadelabs',
  headquarters: '138 Robinson Road #02-50 Singapore',
  unit_token: 'JAD',
  standard: 'ERC20, BEP20',
  basis: 'Kardiachain, Binance Smart Chain',
  address_smart_contract: '0E14BD7C7a45xEB...63208',
  website: 'jadelabs.org',
  social: [],
  socialNetwork: [],
  qr_img_path: 'qr-example.png',
}